# Generated by Django 2.1.3 on 2018-11-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('preparation_time', models.IntegerField()),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('dishes', models.ManyToManyField(to='menu.Dish')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
