# Generated by Django 2.1.3 on 2018-11-23 14:17

from django.db import migrations, models
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.get_image_path),
        ),
    ]
